version: "3"

services:
  simplifry:
    build: .
    ports:
      - "1333:1333"
    volumes:
      - ./data:/app/data
    deploy:
      resources:
        reservations:
          cpus: '30'
          memory: 32G
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
